
print('hola aprendiendo python')
nombre: str= 'pablo'
apellido: str= 'legorburo'
print(f'soy {nombre} y mi apellido es {apellido}')

print(type(nombre))

edad = 24
ciudad = 'Albacete'
tengo_carnet = True


print(type(edad))
print(type(ciudad))
print(type(tengo_carnet))

print(nombre.upper)
print(len (nombre))
print(nombre[0])
print(len (apellido))
print(apellido[-1])
print(len (nombre)-1)

soltero = True


persona = {
    'nombre': 'pablo',
    'edad': 24,
    'ciudad': 'Albacete',
    'soltero': True}
print(persona["nombre"])



compra = ['pan','leche','huevo']

compra.append('frutas')
compra.insert(2,'verduras')
compra.pop(-1)
print(compra)
print('hola aprendiendo python')


culpable = False



if culpable == True:
    print('es culapble')
else:
    print('no es culpable')







